export const LIST_FEEDBACK_REQUEST = "LIST_FEEDBACK_REQUEST";
export const LIST_FEEDBACK_SUCCESS = "LIST_FEEDBACK_SUCCESS";
export const LIST_FEEDBACK_FAIL = "LIST_FEEDBACK_FAIL";

export const SAVE_FEEDBACK_REQUEST = "SAVE_FEEDBACK_REQUEST";
export const SAVE_FEEDBACK_SUCCESS = "SAVE_FEEDBACK_SUCCESS";
export const SAVE_FEEDBACK_FAIL = "SAVE_FEEDBACK_FAIL";

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST";
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_FAIL = "DELETE_FEEDBACK_FAIL";